---
- name: Install maven and clone a remote repository
  hosts: all
  tasks:
    - name: Install maven
      apt:
       name: maven
       state: present
       update_cache: yes
    - name: clone remote git repository
      git:
        repo: https://github.com/MysuraGit/maven.git
        dest: /home/ubuntu/  	
...
